[job]
name = "AAR_test_v6"
out_path = "/home/iaw/DATA2/AAReact/train/test/"

[model]
mol_in_dim = 1536
mol_hidden_dim = 64
unimol_mol_size = "1.1B"
cross_n_heads = 1
cross_dropout = 0
temp_pressure_hidden_dim = 4
fuse_embed_mode = "none"

[train]
seed = 1
epoch = 200
cuda_device =  "cuda"
gpu_idx = [0]

[data]
data_fp = "/home/iaw/DATA2/AAReact/DataSet/debug/debug_df.csv"
cache_fp = "/home/iaw/DATA2/AAReact/DataSet/debug/debug_df_1.1B.pt"
init_unimol_embedding = false
train_valid_test = [0.7, 0.5]
batch_size = 24
seed = 1

[optimizer]
name = "AdamW"
lr = 1.0e-5
  
