[Train]
data_x = "/home/iaw/DATA2/AAReact/DataSet/AtropicAcid_424/data_for_train/rdkit_soap_3_data_x.npy"
data_y = "/home/iaw/DATA2/AAReact/DataSet/AtropicAcid_424/data_for_train/rdkit_soap_3_data_y.npy"
x_label = "/home/iaw/DATA2/AAReact/DataSet/AtropicAcid_424/data_for_train/rdkit_soap_3_x_label.pkl"
data_class = "/home/iaw/DATA2/AAReact/DataSet/AtropicAcid_424/data_for_train/rdkit_soap_3_data_class.pkl"
seed = 1
test_size = 0.2
model_save = "/home/iaw/DATA2/AAReact/train/output/pt/lgb_model_seed_1_split_0-2_hyper2_rdkit_soap.pkl"

[Model]
model_type = "lgb"
colsample_bytree = 0.8
learning_rate = 0.2
max_depth = 8
min_child_samples = 20
n_estimators = 50
num_leaves = 31
reg_alpha = 0.5
reg_lambda = 1.0
subsample = 0.8
