[Train]
data_x = "/home/iaw/DATA2/AAReact/DataSet/AtropicAcid_416/4_gen_feature/rdkit_soap_xtb_3_data_x.npy"
data_y = "/home/iaw/DATA2/AAReact/DataSet/AtropicAcid_416/4_gen_feature/rdkit_soap_xtb_3_data_y.npy"
x_label = "/home/iaw/DATA2/AAReact/DataSet/AtropicAcid_416/4_gen_feature/rdkit_soap_xtb_3_x_label.pkl"
data_class = "/home/iaw/DATA2/AAReact/DataSet/AtropicAcid_416/4_gen_feature/rdkit_soap_xtb_3_data_class.pkl"
seed = 1
test_size = 0.2
model_save = "/home/iaw/DATA2/AAReact/train/output/pt/xgb_model_seed_1_split_0-2_hyper2_soap_xtb.pkl"

[Model]
model_type = "xgb"
colsample_bytree = 0.8
learning_rate = 0.1
max_depth = 10
min_child_weight = 5
n_estimators = 50
reg_alpha = 0.5
reg_lambda = 1.5
subsample = 0.8
